# Generated by Django 2.2.6 on 2020-03-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='age',
            new_name='sage',
        ),
    ]
