# Generated by Django 2.2.6 on 2020-03-25 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200323_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='gdescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
