# Generated by Django 2.2.6 on 2020-03-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_grades_gdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='spoints',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
