# Generated by Django 2.2.6 on 2020-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_students_spoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='spoints2',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
    ]
