# Generated by Django 2.2.6 on 2020-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_students_spoints2'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='isdelete2',
            field=models.NullBooleanField(),
        ),
    ]
