# Generated by Django 2.2.6 on 2020-03-25 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_students_isdelete2'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='gdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='gtime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='gdate',
            field=models.DateField(),
        ),
    ]
