# Generated by Django 2.2.6 on 2020-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20200325_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sage',
            field=models.IntegerField(db_column='ssage'),
        ),
    ]
