# Generated by Django 2.2.6 on 2020-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20200325_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
