# Generated by Django 2.2.6 on 2020-03-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20200325_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='students',
            table='myapp_student',
        ),
    ]
