# Generated by Django 2.2.6 on 2020-03-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20200325_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['sname', '-id']},
        ),
        migrations.AlterModelTable(
            name='grades',
            table='myapp_grade',
        ),
    ]
