# Generated by Django 2.2.6 on 2020-03-26 19:20

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20200325_2207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='isdelete2',
        ),
        migrations.RemoveField(
            model_name='students',
            name='scontend',
        ),
        migrations.RemoveField(
            model_name='students',
            name='spoints',
        ),
        migrations.RemoveField(
            model_name='students',
            name='spoints2',
        ),
        migrations.AddField(
            model_name='students',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='lastTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
